theme: minima
title: Weaving Limitless Possibilities in 3D Art with Unity!
author: edwin
description: 3D developer and passionate 3D art enthusiast. Dedicated to transforming creative visions into immersive virtual worlds, I blend code and visual design to craft engaging game experiences. Every interaction and frame reflects my pure love for 3D artistry. 
